### ISSUE TITLE
Draft a specification on the core system requirements

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/driver-projects#21]

**Comment by hannes-ucsc** [comment]
You and I need to collaborate on this. Feel free to assign issue to me once document is setup.

**Comment by hannes-ucsc** [comment]
@diekhans, would you want to act as a reviewer of the draft document?

**Comment by melissacline** [comment]
Yes!  There's a skeletal draft at https://docs.google.com/document/d/1D6a8AxTaCTHrcNIu4t9tRpPNRyMsbr1DnoBy5TJudy4/edit.

**Comment by diekhans** [comment]
Before designing low-level mechanism, need to document goals
(and more important non-goals) scope of project (3 samples a
week or 3000).  Time line for delivery. What are the requirements on QC?
What is the overall flow of data?  What are the monitoring requirements?
Backup requirements?  Data life cycle?

Essentially, what is being built before how it's built.

**Comment by melissacline** [comment]
Awesome!  How'd you like to submit some input?

**Comment by diekhans** [comment]
I would like to see a goals, scope, and development plan document for
people to react to and know what they are getting (and not getting)
and when they are getting it.

This also needs to cover data security.

Design documented should should demonstrate how it's meeting
the goals.

In other words, what are we building.  It's obvious from the
cancer cats meeting, this is not agreed upon.

**Comment by melissacline** [comment]
Beautiful!  Would you like to put forth any specific questions we should
get addressed?

**Comment by melissacline** [comment]
Duplicate of BD2KGenomics/toil-scripts#41
