### ISSUE TITLE
Run the 4 straggler WCDT RNASeq samples

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/driver-projects#22]
John,
Do you want me to download these to podk or are you going to pull them from SFTP directly?

/data/home/afoye/RNAseq_batch9/DTB-090-Baseline.zip
/data/home/afoye/RNAseq_batch9/DTB-090-Progression.zip
/data/home/afoye/RNAseq_batch9/DTB-097-Progression.zip
/data/home/afoye/RNAseq_batch9/DTB-091-Baseline.zip
-Robert

**Comment by jvivian** [comment]
3 of 4 run.  DTB-090-Pro was corrupted so has not been run yet, although the non-corrupt version is now in S3 and capable of being run at anytime.

Melissa mentioned there may be one more sample to run alongside this one.

**Comment by melissacline** [comment]
Yes, there is one more sample: DTB-077 Pro.  It should be on the FTP site.

**Comment by jvivian** [comment]
Ok, sample is in S3.   Will try and start a run today for:

DTB-090-Progression
DTB-077-Progression
