### ISSUE TITLE
Evaluate suggested sequencing QC metrics, triage

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/driver-projects#23]

**Comment by melissacline** [comment]
Here are some recommended sequencing QC metrics, from the Sanger center.  The quantity in parentheses describes expected parameters.  We don't need to interpret this data, just generate it so that someone else can interpret it...

% mapped (<98% investigate)
%Read 1/2 unmapped ( >2% investigate)
R1/2 GC deviation (40.9% +/-1.5)
GC difference between R1/2 (!>1.5)
Mismatch rate between R1/2 (!>2)

**Comment by diekhans** [comment]
Are these for cancer?  RNA-seq vs exon vs genomic?

**Comment by jvivian** [comment]
My plan was to use picard's bamstats tool:
http://broadinstitute.github.io/picard/command-line-overview.html#CollectAlignmentSummaryMetrics

"BAMStats provides descriptive statistics for coverage, start positions, MAPQ values, mapped read lengths and edit distances. Metrics are given per reference sequence as described in the SAM/BAM file. Metrics can also be generated for individual features such as exon or bait region, if a suitable bed or gtf file is provided.
CLI output can either be as text to command line standard output, or in html format for display as a web page."

If they want other QC then I request that they tell me what tool they would like me to use.

**Comment by melissacline** [comment]
That sounds totally reasonable

**Comment by melissacline** [comment]
Duplicate of BD2KGenomics/toil-scripts#20
