### ISSUE TITLE
Re-S3AM neuroblastoma set (with encryption)

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/driver-projects#32]
I derped up on this and accidentally encrypted everything via master key, so I need to re-s3am these files with unique encryption keys.

**Comment by hannes-ucsc** [comment]
It's good that your are tracking this as an issue. However, we should not track security-related issues in a public repository.

**Comment by hannes-ucsc** [comment]
This issue was moved to BD2KGenomics/security#1
