### ISSUE TITLE
Align 4 remaining WCDT samples

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/driver-projects#36]
DTB-097-Progression
DTB-091-Baseline
DTB-090-Progression
DTB-090-Baseline

**Comment by melissacline** [comment]
These four samples were previously corrupted and could not be run.  The files are in /pod/pstore/projects/su2c/batch9/fastq.

**Comment by jvivian** [comment]
Do you happen to know if Paul already has POD access?  If not, he can also request HIVE access at the same time (for CIRM data).

**Comment by melissacline** [comment]
Good point!

**Comment by melissacline** [comment]
Actually, let's make it simple.  I'm copying over the CIRM data.
