### ISSUE TITLE
Enforce server-side encryption on cgl-driver-projects-encrypted S3 bucket

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/driver-projects#4]

**Comment by jvivian** [comment]
http://s3tools.org/kb/item11.htm

**Comment by hannes-ucsc** [comment]
Just keep in mind that the headers for SSE-C differ from the ones for SSE. So the policy must be adjusted a bit.

**Comment by jvivian** [comment]
Thanks for the info -- I wasn't sure if that was the case or not so I decided to not just blindly implement it.

**Comment by melissacline** [comment]
Move to BD2KGenomics/toil-scripts#40
