### ISSUE TITLE
Transfer USC Stage II and II to S3

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/driver-projects#44]
I'll package it up into tarballs and put it into S3.

**Comment by jvivian** [comment]
Files are located at :
s3://cgl-driver-projects-encrypted/usc/stage2-3/

@melissacline — Files are in S3 now.  Do you want me to make and assign a ticket to run them?

**Comment by melissacline** [comment]
Hi John,

These are RNASeq, right?  If you make up the file that you'd use as input
to the pipeline and send it to me, then I'll turn it into a ticket and get
it assigned.  What's the timeline on these?

Also, what's the word on the ISPY run?  UCSF has been asking.  It's lower
priority than stabilizing the pipelines, but we should get them their
results sooner or later...

Melissa

**Comment by jvivian** [comment]
> These are RNASeq, right? If you make up the file that you'd use as input to the pipeline and send it to me, then I'll turn it into a ticket and get it assigned. 

Ya, I'll make that right now. 

> Also, what's the word on the ISPY run? UCSF has been asking.

Thanks for the reminder.  The issue has been that putting the data in S3, and then pulling it to openstack (where we want to run it), is expensive.  The alternative is to put the data in Ceph, but I haven't been able to access it without an Access Key / Secret Key.  I've emailed Erich and will be meeting with him later today to resolve that.

**Comment by jvivian** [comment]
Below is the config file — I can email it to you if you'd prefer.  Thanks @melissacline 

```
36285_Sample_CTC-5,https://s3-us-west-2.amazonaws.com/cgl-driver-projects-encrypted/usc/stage2-3/36285_Sample_CTC-5.tar.gz
36581_Sample_CTC-6,https://s3-us-west-2.amazonaws.com/cgl-driver-projects-encrypted/usc/stage2-3/36581_Sample_CTC-6.tar.gz
36683_Sample_CTC-7,https://s3-us-west-2.amazonaws.com/cgl-driver-projects-encrypted/usc/stage2-3/36683_Sample_CTC-7.tar.gz
36828_Sample_CTC-8,https://s3-us-west-2.amazonaws.com/cgl-driver-projects-encrypted/usc/stage2-3/36828_Sample_CTC-8.tar.gz
47934_Sample_CTC-9,https://s3-us-west-2.amazonaws.com/cgl-driver-projects-encrypted/usc/stage2-3/47934_Sample_CTC-9.tar.gz
JL09182014,https://s3-us-west-2.amazonaws.com/cgl-driver-projects-encrypted/usc/stage2-3/JL09182014.tar.gz
Sample_31176CTC,https://s3-us-west-2.amazonaws.com/cgl-driver-projects-encrypted/usc/stage2-3/Sample_31176CTC.tar.gz
Sample_36515CTC,https://s3-us-west-2.amazonaws.com/cgl-driver-projects-encrypted/usc/stage2-3/Sample_36515CTC.tar.gz
Sample_58029CTC,https://s3-us-west-2.amazonaws.com/cgl-driver-projects-encrypted/usc/stage2-3/Sample_58029CTC.tar.gz
Sample_68172CTC,https://s3-us-west-2.amazonaws.com/cgl-driver-projects-encrypted/usc/stage2-3/Sample_68172CTC.tar.gz
Sample_78858CTC,https://s3-us-west-2.amazonaws.com/cgl-driver-projects-encrypted/usc/stage2-3/Sample_78858CTC.tar.gz
Sample_78904CTC,https://s3-us-west-2.amazonaws.com/cgl-driver-projects-encrypted/usc/stage2-3/Sample_78904CTC.tar.gz
Sample_78956CTC,https://s3-us-west-2.amazonaws.com/cgl-driver-projects-encrypted/usc/stage2-3/Sample_78956CTC.tar.gz

```
