### ISSUE TITLE
Transfer ISPY Data from PODK to Ceph

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/driver-projects#45]

**Comment by jvivian** [comment]
As we discussed earlier, I'll let @melissacline confirm the sample paths I'll be moving to Ceph.

**Comment by melissacline** [comment]
The data is under  /pod/home/cline/ispy2.
 /pod/home/cline/ispy2/ISPY2015-T0/tarballs  is ready with 41 tarballs
 /pod/home/cline/ispy2/ISPY2015-T1/tarballs  is ready with 55 tarballs
Data is being copied to /pod/home/cline/ispy2/ISPY2015-T0-Batch1/tarballs.  There will be an additional 65 files there.

**Comment by jvivian** [comment]
Started transfers for T0/T1.

**Comment by jvivian** [comment]
Needed multi-part uploading to transfer the larger files which I now got working.  T0 is in Ceph in its entirety, T1 is currently transferring.  

I see 58 files in /pod/home/cline/ispy2/ISPY2015-T0-Batch1/tarballs — Is the transfer still in progress?

**Comment by jvivian** [comment]
As a heads up, there are duplicate file names between these two directories: 

 /pod/home/cline/ispy2/ISPY2015-T0/tarballs  is ready with 41 tarballs
 /pod/home/cline/ispy2/ISPY2015-T1/tarballs  is ready with 55 tarballs

```
(venv)-bash-4.1$ diff -arq /pod/home/cline/ispy2/ISPY2015-T1/tarballs /pod/home/cline/ispy2/ISPY2015-T0/tarballs | grep differ
Files /pod/home/cline/ispy2/ISPY2015-T1/tarballs/1211.tar and /pod/home/cline/ispy2/ISPY2015-T0/tarballs/1211.tar differ
Files /pod/home/cline/ispy2/ISPY2015-T1/tarballs/12743.tar and /pod/home/cline/ispy2/ISPY2015-T0/tarballs/12743.tar differ
Files /pod/home/cline/ispy2/ISPY2015-T1/tarballs/13749.tar and /pod/home/cline/ispy2/ISPY2015-T0/tarballs/13749.tar differ
Files /pod/home/cline/ispy2/ISPY2015-T1/tarballs/15637.tar and /pod/home/cline/ispy2/ISPY2015-T0/tarballs/15637.tar differ
Files /pod/home/cline/ispy2/ISPY2015-T1/tarballs/20226.tar and /pod/home/cline/ispy2/ISPY2015-T0/tarballs/20226.tar differ
Files /pod/home/cline/ispy2/ISPY2015-T1/tarballs/23892.tar and /pod/home/cline/ispy2/ISPY2015-T0/tarballs/23892.tar differ
Files /pod/home/cline/ispy2/ISPY2015-T1/tarballs/26196.tar and /pod/home/cline/ispy2/ISPY2015-T0/tarballs/26196.tar differ
Files /pod/home/cline/ispy2/ISPY2015-T1/tarballs/30119.tar and /pod/home/cline/ispy2/ISPY2015-T0/tarballs/30119.tar differ
Files /pod/home/cline/ispy2/ISPY2015-T1/tarballs/33325.tar and /pod/home/cline/ispy2/ISPY2015-T0/tarballs/33325.tar differ
Files /pod/home/cline/ispy2/ISPY2015-T1/tarballs/33341.tar and /pod/home/cline/ispy2/ISPY2015-T0/tarballs/33341.tar differ
Files /pod/home/cline/ispy2/ISPY2015-T1/tarballs/34306.tar and /pod/home/cline/ispy2/ISPY2015-T0/tarballs/34306.tar differ
Files /pod/home/cline/ispy2/ISPY2015-T1/tarballs/41691.tar and /pod/home/cline/ispy2/ISPY2015-T0/tarballs/41691.tar differ
Files /pod/home/cline/ispy2/ISPY2015-T1/tarballs/45597.tar and /pod/home/cline/ispy2/ISPY2015-T0/tarballs/45597.tar differ
Files /pod/home/cline/ispy2/ISPY2015-T1/tarballs/46404.tar and /pod/home/cline/ispy2/ISPY2015-T0/tarballs/46404.tar differ
Files /pod/home/cline/ispy2/ISPY2015-T1/tarballs/55731.tar and /pod/home/cline/ispy2/ISPY2015-T0/tarballs/55731.tar differ
Files /pod/home/cline/ispy2/ISPY2015-T1/tarballs/81451.tar and /pod/home/cline/ispy2/ISPY2015-T0/tarballs/81451.tar differ
Files /pod/home/cline/ispy2/ISPY2015-T1/tarballs/82990.tar and /pod/home/cline/ispy2/ISPY2015-T0/tarballs/82990.tar differ
Files /pod/home/cline/ispy2/ISPY2015-T1/tarballs/8916.tar and /pod/home/cline/ispy2/ISPY2015-T0/tarballs/8916.tar differ
```

**Comment by melissacline** [comment]
I looked at the error log for packaging the files to ISPY2015-T0-Batch1, and there were some problems.  I'd inadvertently ended up with two distinct jobs that were running at the same time and overwriting each other.  So, I killed both and am restarting the packaging.  It will probably take a while...

The T0 and T1 sets contain data from the same patients measured at different timepoints.  So it's to be expected (and good) that there are some duplicate names, if just the sample name is in there.  Would you like me to rename the tarballs to pull in the timepoint name?

**Comment by jvivian** [comment]
That'd be great —The script I wrote to do uploads skips files that are
already in Ceph, so all of the T1 dupliate file names were not uploaded.

**Comment by melissacline** [comment]
Done - all T1 files renamed!

**Comment by jvivian** [comment]
Hey Melissa,

I only see 59 files in the `/pod/home/cline/ispy2/ISPY2015-T0-Batch1/tarballs` directory and several of the file sizes are only 10k.   Is a transfer still currently in progress?

**Comment by melissacline** [comment]
It turns out that there were only 60 samples with "real" data.  57, 298, 24513, 83989 and 87602 were all controls of some sort (and had tiny tarballs because there wasn't really any data there).  There were an additional 6 samples that were still getting repackaged when stacker went down yesterday.  I'm repackaging them now.  They are 
Sample_89011
Sample_90013
Sample_916
Sample_93360
Sample_95244
Sample_98798

**Comment by jvivian** [comment]
Great, thanks Melissa! I'll wait until those are done transferring then
throw them in Ceph.

**Comment by jvivian** [comment]
Done! I'll create another ticket for running the data.
